<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminForm.Master" AutoEventWireup="true" CodeBehind="UpdateOrDeleteStudents.aspx.cs" Inherits="StudentManagementSystem.Admin.UpdateOrDeleteStudents" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
        <style type="text/css">
    .auto-style5 {
        font-size: large;
    }
            .auto-style6 {
                font-size: large;
                color: #0066FF;
            }
        </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div>
    <asp:GridView ID="GridView1" runat="server"  BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="auto-style5" DataKeyNames="RegNo" DataSourceID="SqlDataSource1" OnRowCommand="GridView1_RowCommand" OnRowDeleting="GridView1_RowDeleting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:BoundField DataField="RegNo" HeaderText="RegNo" InsertVisible="False" ReadOnly="True" SortExpression="RegNo" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
            <asp:BoundField DataField="Gender" HeaderText="Gender" SortExpression="Gender" />
            <asp:BoundField DataField="Course" HeaderText="Course" SortExpression="Course" />
            <asp:BoundField DataField="FinalFee" HeaderText="FinalFee" SortExpression="FinalFee" />
            <asp:BoundField DataField="FeePaid" HeaderText="FeePaid" SortExpression="FeePaid" />
            <asp:BoundField DataField="MobileNo" HeaderText="MobileNo" SortExpression="MobileNo" />
            <asp:BoundField DataField="EmailId" HeaderText="EmailId" SortExpression="EmailId" />
            <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
            <asp:BoundField DataField="Pincode" HeaderText="Pincode" SortExpression="Pincode" />
            <asp:BoundField DataField="Graduation" HeaderText="Graduation" SortExpression="Graduation" />
            <asp:BoundField DataField="Branch" HeaderText="Branch" SortExpression="Branch" />
            <asp:BoundField DataField="YOP" HeaderText="YOP" SortExpression="YOP" />
            <asp:BoundField DataField="CGPA" HeaderText="CGPA" SortExpression="CGPA" />
        </Columns>
        <FooterStyle BackColor="#CCCC99" />
        <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
        <RowStyle BackColor="#F7F7DE" />
        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#FBFBF2" />
        <SortedAscendingHeaderStyle BackColor="#848384" />
        <SortedDescendingCellStyle BackColor="#EAEAD3" />
        <SortedDescendingHeaderStyle BackColor="#575357" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SMSConnectionString %>" DeleteCommand="DELETE FROM [TBLSTUDENTS] WHERE [RegNo] = @RegNo" InsertCommand="INSERT INTO [TBLSTUDENTS] ([Name], [Password], [Gender], [Course], [FinalFee], [FeePaid], [MobileNo], [EmailId], [Address], [Pincode], [Graduation], [Branch], [YOP], [CGPA]) VALUES (@Name, @Password, @Gender, @Course, @FinalFee, @FeePaid, @MobileNo, @EmailId, @Address, @Pincode, @Graduation, @Branch, @YOP, @CGPA)" ProviderName="<%$ ConnectionStrings:SMSConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [TBLSTUDENTS]" UpdateCommand="UPDATE [TBLSTUDENTS] SET [Name] = @Name, [Password] = @Password, [Gender] = @Gender, [Course] = @Course, [FinalFee] = @FinalFee, [FeePaid] = @FeePaid, [MobileNo] = @MobileNo, [EmailId] = @EmailId, [Address] = @Address, [Pincode] = @Pincode, [Graduation] = @Graduation, [Branch] = @Branch, [YOP] = @YOP, [CGPA] = @CGPA WHERE [RegNo] = @RegNo">
        <DeleteParameters>
            <asp:Parameter Name="RegNo" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Gender" Type="String" />
            <asp:Parameter Name="Course" Type="String" />
            <asp:Parameter Name="FinalFee" Type="Decimal" />
            <asp:Parameter Name="FeePaid" Type="Decimal" />
            <asp:Parameter Name="MobileNo" Type="Int64" />
            <asp:Parameter Name="EmailId" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="Pincode" Type="Int32" />
            <asp:Parameter Name="Graduation" Type="String" />
            <asp:Parameter Name="Branch" Type="String" />
            <asp:Parameter Name="YOP" Type="Int32" />
            <asp:Parameter Name="CGPA" Type="Int32" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Gender" Type="String" />
            <asp:Parameter Name="Course" Type="String" />
            <asp:Parameter Name="FinalFee" Type="Decimal" />
            <asp:Parameter Name="FeePaid" Type="Decimal" />
            <asp:Parameter Name="MobileNo" Type="Int64" />
            <asp:Parameter Name="EmailId" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="Pincode" Type="Int32" />
            <asp:Parameter Name="Graduation" Type="String" />
            <asp:Parameter Name="Branch" Type="String" />
            <asp:Parameter Name="YOP" Type="Int32" />
            <asp:Parameter Name="CGPA" Type="Int32" />
            <asp:Parameter Name="RegNo" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
        <br />
        <asp:Label ID="lblMessage" runat="server" CssClass="auto-style6"></asp:Label>
</div>
</asp:Content>
