<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminForm.Master" AutoEventWireup="true" CodeBehind="UpdateOrDeleteCourses.aspx.cs" Inherits="StudentManagementSystem.Admin.UpdateOrDeleteCourses" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
        <style type="text/css">
    .auto-style5 {
        font-size: xx-large;
    }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="background-color : aliceblue;">
    <div>
        <h1 class="auto-style1">Update (or) Delete Courses:</h1>
    </div>
    <div>

        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="CourseId" DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CssClass="auto-style5" Width="1094px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="CourseId" HeaderText="CourseId" InsertVisible="False" ReadOnly="True" SortExpression="CourseId" />
                <asp:BoundField DataField="CourseName" HeaderText="CourseName" SortExpression="CourseName" />
                <asp:BoundField DataField="Fee" HeaderText="Fee" SortExpression="Fee" />
                <asp:BoundField DataField="Duration" HeaderText="Duration" SortExpression="Duration" />
            </Columns>
            <FooterStyle BackColor="#CCCC99" />
            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
            <RowStyle BackColor="#F7F7DE" />
            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FBFBF2" />
            <SortedAscendingHeaderStyle BackColor="#848384" />
            <SortedDescendingCellStyle BackColor="#EAEAD3" />
            <SortedDescendingHeaderStyle BackColor="#575357" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SMSConnectionString2 %>" DeleteCommand="DELETE FROM [TBLCOURSES] WHERE [CourseId] = @CourseId" InsertCommand="INSERT INTO [TBLCOURSES] ([CourseName], [Fee], [Duration]) VALUES (@CourseName, @Fee, @Duration)" ProviderName="<%$ ConnectionStrings:SMSConnectionString2.ProviderName %>" SelectCommand="SELECT * FROM [TBLCOURSES]" UpdateCommand="UPDATE [TBLCOURSES] SET [CourseName] = @CourseName, [Fee] = @Fee, [Duration] = @Duration WHERE [CourseId] = @CourseId">
            <DeleteParameters>
                <asp:Parameter Name="CourseId" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="CourseName" Type="String" />
                <asp:Parameter Name="Fee" Type="Decimal" />
                <asp:Parameter Name="Duration" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="CourseName" Type="String" />
                <asp:Parameter Name="Fee" Type="Decimal" />
                <asp:Parameter Name="Duration" Type="String" />
                <asp:Parameter Name="CourseId" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>

        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />

    </div>
</div>
</asp:Content>
